color = input("Please type your favorite color: ")
print("Your favorite color is: " + color)
animal = input("Please type your favorite animal? ")
print("Your favorite animal is: " + animal)
snack = input("Please type your favorite snack? ")
print("Your favorite snack is: " + snack)
print("\nYour " + color + " " + animal + " is eating your " + snack + "!")