print("Please enter the following information:")

#Inputs
first_name = input("First Name: ")
last_name = input("Last Name: ")
email = input("Email address: ")
phone = input("Phone number: ")
job = input("Job title: ")
Id_number = input("ID Nunber: ")
hair = input("Hair color: ")
eyes = input("Eye color: ")
month = input("Month that you started the training: ")
finished = input("Did you finish the training?(yes/no): ")

print("The ID Card is:")
print("-----------------------------------------")
print(f"{last_name.upper()}, {first_name.capitalize()}")
print(job.title())
print(f"ID: {Id_number} \n")
print(email.lower())
print(phone + "\n")
print(f"Hair: {hair.capitalize()} \t Eyes:{eyes.capitalize()}".expandtabs(10))
print(f"Month: {month.capitalize()} \t Training: {finished.capitalize()}".expandtabs(10))
print("-----------------------------------------")